### PR TITLE
[RELEASE-1.11] Move to Golang version 1.21 (#546)

### PR DESCRIPTION
**Pull request by skonto**
## Proposed Changes

* Required for https://github.com/openshift-knative/serving/pull/591.
* We need the same for 1.12 but needs to be done manually.
* Afaik we are already building with 1.21.x downstream so it should be safe.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve
/hold let's wait until we know that we can productize it with go 1.21

**Comment by skonto** [comment]
@ReToCode it seems we are ok with the productization https://redhat-internal.slack.com/archives/CF5ANN61F/p1705515999236559

**Comment by ReToCode** [comment]
👍 
/unhold

**Pull request merged**
