### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
infra?
> [36mINFO[0m[2024-10-07T06:02:48Z] Build src-amd64 previously failed from an infrastructure error (FetchImageContentFailed), retrying... 
[36mINFO[0m[2024-10-07T06:03:48Z] Created build "src-amd64"

**Comment by ReToCode** [comment]
yes,

```
error: error creating buildah builder: initializing source docker://registry.build10.ci.openshift.org/ci/managed-clonerefs@sha256:a163a9a78b921e3c553bf07ae460a942d32b90319eae00eb036dd34cb10b08aa: pinging container registry registry.build10.ci.openshift.org: received unexpected HTTP status: 503 Service Unavailable
```

/retest

**Comment by ReToCode** [comment]
No luck,

```
error: error creating buildah builder: initializing source docker://registry.build10.ci.openshift.org/ci/managed-clonerefs@sha256:a163a9a78b921e3c553bf07ae460a942d32b90319eae00eb036dd34cb10b08aa: pinging container registry registry.build10.ci.openshift.org: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by ReToCode** [comment]
Let's see if CI has a better day tomorrow.

**Pull request closed without merging**
