### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
Writing manifest to image destination
[2/2] STEP 2/13: ENV "BUILD_LOGLEVEL"="0"
[2/2] STEP 3/13: ARG TARGETARCH
[2/2] STEP 4/13: COPY --from=tools /usr/share/openshift/linux_$TARGETARCH/oc.rhel8 /usr/bin/oc
[2/2] STEP 5/13: RUN ln -s /usr/bin/oc /usr/bin/kubectl
[2/2] STEP 6/13: RUN yum install -y httpd-tools
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.

This system is not registered with an entitlement server. You can use subscription-manager to register.

rhel-8-baseos                                   0.0  B/s |   0  B     00:04    
Errors during downloading metadata for repository 'rhel-8-baseos':
  - Curl error (7): Couldn't connect to server for http://base-4-17-rhel8.ocp.svc/rhel-8-baseos/repodata/repomd.xml [Failed to connect to base-4-17-rhel8.ocp.svc port 80: Connection refused]
Error: Failed to download metadata for repo 'rhel-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
cc @dsimansk

**Comment by skonto** [comment]
Fails for Eventing too: https://prow.ci.openshift.org/log?container=test&id=1871548820156846080&job=pull-ci-openshift-knative-eventing-release-v1.16-417-test-e2e

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
