### PR TITLE
[RELEASE-v1.15] Fix configuration metadata inconsistency (#15601)

### PR DESCRIPTION
**Pull request by skonto**
**What this PR does / why we need it**:

- Backports the upstream related issue.

**Which issue(s) this PR fixes**:

JIRA:

**Does this PR needs for other branches**:

YES. v1.16

**Does this PR (patch) needs to update/drop in the future?**:

NONE

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
```
Registry server Password: <<non-empty>>
error: build error: Failed to push image: trying to reuse blob sha256:e0348fdb2685077d22116d294a90a253709aba78815882a57fcc536b22dcae2f at destination: unable to retrieve auth token: invalid username/password: authentication required
10:59:43.051 INFO:    Image builds finished

[ingress pod log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-knative_serving/1056/pull-ci-openshift-knative-serving-release-v1.15-417-test-e2e-tls/1868590656968986624/artifacts/test-e2e-tls/test/artifacts/gather-knative/quay-io-openshift-knative-must-gather-sha256-f1cd829ea23838ac3e9b7e3a42269ea34a32e7af6a5465f9d5d21a3caf3ce446/openshift-serverless/pods/knative-openshift-ingress-5c696db679-4xkrm-describe.log)
  Warning  Failed          4m26s (x4 over 5m52s)  kubelet            Error: ErrImagePull
  Warning  Failed          4m11s (x6 over 5m51s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff         45s (x21 over 5m51s)   kubelet            Back-off pulling image "image-registry.openshift-image-registry.svc:5000/openshift-marketplace/serverless-ingress"
  

11:06:09.404 DEBUG:   [[ $(oc get ClusterServiceVersion serverless-operator.v1.35.0 -n openshift-serverless -o jsonpath='{.status.phase}') != Succeeded ]] : Waiting until non-zero (max 300 sec.)
.............................................................................................................................................................................................................................................................................................................
11:11:42.771 ERROR:   Time out of 300 exceeded
```

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-activator-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-hpa-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-cleanup-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-controller-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-dataplane-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-default-domain-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-load-test-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-queue-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-real-traffic-test-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-reconciliation-delay-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-rollout-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-scale-from-zero-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-storage-version-migration-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-autoscale-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-failing-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-grpc-ping-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-hellohttp2-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-hellovolume-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-helloworld-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-httpproxy-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv1-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv2-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-readiness-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-revisionfailure-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-runtime-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-servingcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-sidecarcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-singlethreaded-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-slowstart-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-timeout-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-volumes-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-wsserver-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-webhook-115"

**Comment by skonto** [comment]
@ReToCode this still fails.

**Comment by skonto** [comment]
>
Registry server Email: 
Registry server Password: <<non-empty>>
error: build error: Failed to push image: trying to reuse blob sha256:e0348fdb2685077d22116d294a90a253709aba78815882a57fcc536b22dcae2f at destination: unable to retrieve auth token: invalid username/password: authentication required
12:44:52.926 DEBUG:   Undo potential changes to the CSV to not pollute the repository.
Warning: Group 'system:unauthenticated' not found
clusterrole.rbac.authorization.k8s.io/system:image-puller added: "system:unauthenticated"
Warning: Group 'system:serviceaccounts:openshift-serverless' not found
clusterrole.rbac.authorization.k8s.io/system:image-puller added: "system:serviceaccounts:openshift-serverless"

**Comment by skonto** [comment]
Another error now
```

: initialize expand_less	0s
{  could not initialize namespace: could not set up namespace for test: Internal error occurred: resource quota evaluation timed out}
```

**Pull request merged**
