### PR TITLE
[release-v1.5] SRVKS-981 Multiarch test images

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.redhat.com/browse/SRVKS-981

* Include github action for building multiarch test images, similar to what was done for eventing-kafka-broker: [link](https://github.com/openshift-knative/eventing-kafka-broker/blob/main/.github/workflows/multiarch-build.yaml). This github action references the [shared one in openshift-knative/hack repo](https://github.com/openshift-knative/hack/blob/main/.github/workflows/multiarch-build.yaml)
* Remove upstream github actions as we don't want to run them midstream (same is done for eventing-kafka-broker).
* Allows specifying TEST_IMAGE_TAG and KO_FLAGS for the `ko` build. These params will be passed by the shared github action

The images will be built upon any commit on the release branch. And will be published to `https://quay.io/repository/openshift-knative/serving/<IMAGE_NAME>`.  [Example](https://quay.io/repository/openshift-knative/serving/autoscale)

### CODE REVIEW

**Comment by skonto** [comment]
Next step is to enable actions in this repo?

**Comment by mgencur** [comment]
> Next step is to enable actions in this repo?

Yes. Similar to how it's done in eventing-kafka-broker.

**Comment by mgencur** [comment]
OK. Will send PRs manually against the other branches.

**Comment by mgencur** [comment]
Created
https://github.com/openshift-knative/serving/pull/28
https://github.com/openshift-knative/serving/pull/29
https://github.com/openshift-knative/serving/pull/30

**Pull request merged**
