### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
Uploading finished
The ImageStreamTag "origin-base:latest" is invalid: from: Error resolving ImageStreamTag origin-base:latest in namespace openshift-marketplace: unable to find latest tagged image
make[1]: *** [images] Error 1
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
