### PR TITLE
[main] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by skonto** [comment]
@mgencur I guess we will have to validate this after it is merged? Can we build 1.15 with this? cc @dsimansk fyi could you take a look?

**Review by creydr — APPROVED** [review]
/lgtm

Removes the konflux configs from main/release-next again

**Comment by creydr** [comment]
/cc @skonto 
Could you PTAL? We remove the konflux config for main/release-next again, as this is mostly noise ATM

**Pull request merged**
