### PR TITLE
[release-v1.15] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by mgencur** [comment]
/retest-required

Retest as https://github.com/openshift-knative/serverless-operator/pull/2835 was merged.

**Comment by skonto** [comment]
See for this failure [here](https://redhat-internal.slack.com/archives/CFUGK0K9R/p1726478793020679)

**Comment by skonto** [comment]
Image generation seems broken. cc @mgencur

**Comment by ReToCode** [comment]
I see, so let's merge https://github.com/openshift-knative/serving/pull/847 first. We can override the TLS tests, as they'll be covered with https://github.com/openshift-knative/serving/pull/801 (I'm working on that).

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
