### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
	0s
{Failed  panic: test timed out after 10m0s
running tests:
	TestGRPCUnaryPing (10m0s)

```

**Comment by skonto** [comment]
It seems it [fails](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-knative-serving-release-next-413-test-e2e-aws-413-c/1838388757552697344) in periodics too.

**Comment by ReToCode** [comment]
Not that I'm aware of. No idea 🤷

**Comment by skonto** [comment]
It seems quite deterministic.

**Comment by skonto** [comment]
grpc 1.67.0 brings this change https://github.com/grpc/grpc-go/blob/bcf9171a20e44ed81a6eb152e3ca9e35b2c02c5d/credentials/tls.go#L129.

**Comment by skonto** [comment]
Adding it here for ref, still investigating.
We have an edge terminated route and obviously alpn is empty. Haproxy has this: https://github.com/openshift/router/blob/master/images/router/haproxy/conf/haproxy-config.template#L739.
However not sure if we can have `appProtocol: h2c` for all cases since we had a problem with a related port config , https://issues.redhat.com/browse/SRVKS-1232.

**Comment by skonto** [comment]
Reverting passes see: https://github.com/openshift-knative/serving/pull/893.

**Comment by ReToCode** [comment]
Hm nice find. To be honest, no idea. Could we probably also just set `GRPC_ENFORCE_ALPN_ENABLED`? So we could keep the upstream changes?

**Comment by skonto** [comment]
Ok checking https://github.com/openshift-knative/serving/pull/894. I will talk to router folks to open a bug as well. Going forward we need this, setting the env var is temporary unless we patch grpc itself and remove that alpn check (a bit ugly).

**Comment by skonto** [comment]
@ReToCode I suspect it does not get the fix, probably we will have to close it and wait for the next one?

**Comment by skonto** [comment]
Wait it seems the errors are not related.

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
