### PR TITLE
[release-1.11] sync with upstream to include CVE patches

### PR DESCRIPTION
**Pull request by ReToCode**
**What this PR does / why we need it**:
- sync with upstream to include CVE patches
- includes `openshift/patches/010-secure-pod-defaults.patch` from main branch

**Which issue(s) this PR fixes**:

JIRA: https://issues.redhat.com/browse/SRVKS-1159

### CODE REVIEW

**Comment by skonto** [comment]
operator tests:

```
  Conditions:
    Last Transition Time:  2023-10-12T08:58:59Z
    Status:                True
    Type:                  DependenciesInstalled
    Last Transition Time:  2023-10-12T08:59:33Z
    Message:               Waiting on deployments: net-kourier-controller, 3scale-kourier-gateway
    Reason:                NotReady
    Status:                False
    Type:                  DeploymentsAvailable
    Last Transition Time:  2023-10-12T08:58:59Z
    Status:                True
    Type:                  InstallSucceeded
    Last Transition Time:  2023-10-12T08:59:33Z
    Message:               Waiting on deployments: net-kourier-controller, 3scale-kourier-gateway
    Reason:                NotReady
    Status:                False
    Type:                  Ready
    Last Transition Time:  2023-10-12T08:58:44Z
    Status:                True
    Type:                  VersionMigrationEligible
```

**Comment by skonto** [comment]
```
  Warning  Unhealthy       6m7s (x61 over 16m)  kubelet            Liveness probe errored: missing probe handler for net-kourier-controller-5664778ddd-zcc2x_knative-serving-ingress(b360c213-de7c-432e-99c8-a0a2ba28f0db):controller
  Warning  Unhealthy       67s (x106 over 16m)  kubelet            Readiness probe errored: missing probe handler for net-kourier-controller-5664778ddd-zcc2x_knative-serving-ingress(b360c213-de7c-432e-99c8-a0a2ba28f0db):controller
```

**Comment by ReToCode** [comment]
/hold

wait for https://github.com/openshift-knative/serverless-operator/pull/2310 to be in and S-O builds to be stable again.

**Comment by skonto** [comment]
I will debug this on 4.10 seems suspicious.

**Comment by ReToCode** [comment]
Ah we also need https://github.com/openshift/release/pull/44332 first

**Comment by ReToCode** [comment]
/unhold

@skonto , @nak3 please review.

**Pull request merged**
