### PR TITLE
[RELEASE-v1.6][SRVKS-971] Apply common name patch

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch adds the patch https://github.com/knative-sandbox/control-protocol/commit/4472b318e332f2059f919e2d115965ada4833a69

### CODE REVIEW

**Comment by nak3** [comment]
/hold

This does not meet the timeline for 1.26. I will send the fix against 1.7.

**Comment by skonto** [comment]
@nak3 1.6 is for 1.27 we have until next week why it does not meet the dealine?

**Comment by nak3** [comment]
/hold cancel
Ah, sorry. I wrongly counted the number. It meets the deadline then.

**Comment by nak3** [comment]
Closing as cherry-picked by https://github.com/openshift-knative/serving/pull/72

**Pull request closed without merging**
