### PR TITLE
[RELEASE-1.13] Fix the perf patch

### PR DESCRIPTION
**Pull request by skonto**
**What this PR does / why we need it**:

* Fixes the issue with the perf patch see https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/branch-ci-openshift-knative-serving-release-v1.13-414-images/1754768324287270912/build-log.txt
* Required by https://github.com/openshift-knative/serverless-operator/pull/2524

### CODE REVIEW

**Comment by skonto** [comment]
`{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}`

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
