### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
./hack/images.sh image-registry.openshift-image-registry.svc:5000/openshift-marketplace
./hack/lib/vars.bash: line 3: basenc: command not found
Branch and Tag:  - 
```

**Comment by skonto** [comment]
```
The ImageStreamTag "ubi-minimal:latest" is invalid: from: Error resolving ImageStreamTag ubi-minimal:latest in namespace openshift-marketplace: unable to find latest tagged image
```

**Comment by skonto** [comment]
@cardil could you take a look at https://github.com/openshift-knative/serving/pull/946#issuecomment-2446238504?

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
