### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by ReToCode** [comment]
```
  startingCSV: "serverless-operator.v1.35.0"
```

probably this is now a bit broken until 1.35 is properly release? @skonto

**Comment by skonto** [comment]
I am not sure. Yesterday it was using the same version and passed.

**Comment by skonto** [comment]
```
07:34:47.096 ERROR:   🚨 Error (code: 105) occurred at ./hack/lib/serverless.bash:111, with command: return 105
07:34:47.099 INFO:    Dumping state...
07:34:47.101 DEBUG:   Environment variables:
```

**Comment by skonto** [comment]
> + eval '[[ $(oc get ClusterServiceVersion serverless-operator.v1.35.0 -n openshift-serverless -o jsonpath='\''{.status.phase}'\'') != Succeeded ]]'
> +++ oc get ClusterServiceVersion serverless-operator.v1.35.0 -n openshift-serverless -o 'jsonpath={.status.phase}'
> ++ [[ Installing != Succeeded ]]
> + seconds=301
> + echo -n .
> + sleep 1
> + [[ 301 -gt 300 ]]
> + echo ''
> + logger.error 'Time out of 300 exceeded'
> ++ date +%H:%M:%S.%3N
> + echo '07:34:46.907 ERROR:   Time out of 300 exceeded'

**Comment by skonto** [comment]
> sha256:9bbeec1e3a61952200fed258da8b5ddc6612b5cd9a435381e20f100471501476 in registry.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8: unauthorized: access to the requested resource is not authorized
  Warning  Failed          4m35s (x4 over 6m9s)   kubelet            Error: ErrImagePull
  Warning  Failed          4m20s (x6 over 6m8s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff         64s (x20 over 6m8s)    kubelet            Back-off pulling image "registry.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8@sha256:9bbeec1e3a61952200fed258da8b5ddc6612b5cd9a435381e20f100471501476"

**Comment by skonto** [comment]
This is broken due to https://github.com/openshift-knative/serverless-operator/commit/ade4f8cd447eb6424b62ea7045a9a9d2e1c36fe0

**Comment by skonto** [comment]
It seems that this stills fails with the same error: 

```
 Warning  Failed          4m36s (x4 over 6m9s)   kubelet            Failed to pull image "registry.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8@sha256:9bbeec1e3a61952200fed258da8b5ddc6612b5cd9a435381e20f100471501476": reading manifest sha256:9bbeec1e3a61952200fed258da8b5ddc6612b5cd9a435381e20f100471501476 in registry.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8: unauthorized: access to the requested resource is not authorized
  Warning  Failed          4m36s (x4 over 6m9s)   kubelet            Error: ErrImagePull
  Warning  Failed          4m21s (x6 over 6m8s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff         69s (x20 over 6m8s)    kubelet            Back-off pulling image "registry.redhat.io/openshift-serverless-1/kn-client-cli-artifacts-rhel8@sha256:9bbeec1e3a61952200fed258da8b5ddc6612b5cd9a435381e20f100471501476"
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
