### PR TITLE
[RELEASE-1.13] Back-port multi-container probing

### PR DESCRIPTION
**Pull request by ReToCode**
# Description
- Back-ports https://github.com/knative/serving/pull/14853

# Do we need to patch other branches?
No, this will be in 1.14 upstream

JIRA: https://issues.redhat.com/browse/SRVKS-1186

/assign @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
@skonto I don't think we need a git patch for this, it will be in 1.14 and the back-port applies without changes. WDYT?

**Comment by skonto** [comment]
Yes I can't think of an issue. What will happen if someone downgrades I guess we dont support it right?

**Pull request merged**
