### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
{  error occurred handling build knative-serving-test-singlethreaded-amd64: the build knative-serving-test-singlethreaded-amd64 failed after 8m51s with reason DockerBuildFailed: Dockerfile build strategy has failed.}
```

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
