### PR TITLE
[release-v1.7] Fix invalid manifests

### PR DESCRIPTION
**Pull request by nak3**
This patch contains the following fixes:
- Add missing new line in https://github.com/openshift-knative/serving/pull/176 (`domainmapping-controller.yaml`)
- Add missing seccomp CRD for `1-serving-crds.yaml` in https://github.com/openshift-knative/serving/pull/194

Also, this patch cherry-picks the following PRs for maintainability:
- https://github.com/openshift-knative/serving/pull/81
- https://github.com/openshift-knative/serving/pull/89
- https://github.com/openshift-knative/serving/pull/148

### CODE REVIEW

**Comment by nak3** [comment]
/cc @skonto @ReToCode @mgencur

https://github.com/openshift-knative/serverless-operator/pull/1990 verified this change.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
@nak3 A missing new line makes the yaml invalid?

**Comment by nak3** [comment]
> @nak3 A missing new line at the end of file makes the yaml invalid?

Yes, `openshift/release/resolve.sh` assumed that the files have it so it caused the following invalid yaml:
https://github.com/openshift-knative/serverless-operator/pull/1990/commits/80d84019922d6474614ea6b0f8d24dddd0027bd9#diff-afcb8cb79053a14a8bd4e3cf30f5342402b75a7e615010efc04daa68de18889aR6344

**Pull request merged**
