### PR TITLE
Fix GO-2024-2659 (#15547)

### PR DESCRIPTION
**Pull request by skonto**
**What this PR does / why we need it**:

- See https://github.com/knative/serving/pull/15547

### CODE REVIEW

**Comment by skonto** [comment]
```
Vulnerability #1: GO-2024-3106
    Stack exhaustion in Decoder.Decode in encoding/gob
  More info: https://pkg.go.dev/vuln/GO-2024-3106
  Standard library
    Found in: encoding/gob@go1.21.13
    Fixed in: encoding/gob@go1.22.7
    Example traces found:
Error:       #1: cmd/activator/main.go:[20](https://github.com/openshift-knative/serving/actions/runs/11163315729/job/31029963944?pr=904#step:4:21)5:2: activator.main calls websocket.ManagedConnection.Shutdown, which eventually calls gob.Decoder.Decode

```

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

/hold for the go version thing

**Pull request merged**
