### PR TITLE
[MAIN] Update k8s repo

### PR DESCRIPTION
**Pull request by skonto**
**What this PR does / why we need it**:

- Old google repos are removed. See discussion [here](https://redhat-internal.slack.com/archives/CD87JDUB0/p1709542708643019).

Note: This needs to be merged first so it can be tested.

### CODE REVIEW

**Comment by skonto** [comment]
See https://github.com/openshift-knative/hack/pull/128 as well.

**Review by ReToCode — APPROVED** [review]
/lgtm

**Pull request merged**
