### PR TITLE
[release-v1.9] Backport all upstream fixes since branch-cut

### PR DESCRIPTION
**Pull request by ReToCode**
**What this PR does / why we need it**:
This patch backports all upstream patches since branch-cut:
The commit diffs are in https://github.com/openshift-knative/serving/compare/release-v1.9...knative:serving:release-1.9

**Which issue(s) this PR fixes**:
NONE

**Does this PR needs for other branches**:
NONE

**Does this PR (patch) needs to update/drop in the future?**:
NONE

/assign @nak3, @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
`Validate / Lint (pull_request)`
I'd rather not change cherry-picked commits, so ignoring those.

**Comment by skonto** [comment]
Lint failures are shell related so we can ignore them.
/lgtm
/hold for @nak3 if he wants to comment.

**Comment by ReToCode** [comment]
As per slack, for latter reference: We have the last commit already and the second last does not apply because we delete the files there.

**Pull request merged**
