### PR TITLE
:robot: Triggering CI on branch 'release-next' after syncing to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by ReToCode** [comment]
```
  *[2024-10-22T06:45:14Z]NoClusters: No clusters in pool are ready to be claimed 
```

/test 416-test-e2e-aws-416

**Comment by skonto** [comment]
```
16:11:25.925 INFO:    Check if CatalogSource is installed
16:11:26.102 INFO:    Installing CatalogSource
./hack/lib/catalogsource.bash: line 28: FORCE_KONFLUX_INDEX: unbound variable
make[1]: *** [Makefile:28: install-serving] Error 1
make[1]: Leaving directory '/tmp/knative.y0KvV4Ii/tmp.pJabfa7MIJ'
```

**Comment by mgencur** [comment]
@skonto Sorry, sent a fix here: https://github.com/openshift-knative/serverless-operator/pull/2969

It's problematic to use the Konflux Index image without modifications. Serving replaces some release artifacts in the manifests dir and then requires rebuilding the stuff from scratch.
Same applies to Eventing.

**Comment by mgencur** [comment]
The PR was merged. Re-testing.

/test 416-test-e2e-aws-416

**Comment by serverless-qe** [comment]
OCF Webhook is merging this PR

**Pull request merged**
