### PR TITLE
[release-v1.15] Add Konflux configurations

### PR DESCRIPTION
**Pull request by serverless-qe**
Add Konflux components and pipelines

### CODE REVIEW

**Comment by pierDipi** [comment]
```
process exited with error: exec: not startedsubprocess exited with status 1
Error: building at STEP "RUN ./openshift/in-docker-patch.sh": exit status 1
```

**Comment by pierDipi** [comment]
in Konflux we build everything we build in CI, but there is a way of excluding images

**Comment by skonto** [comment]
I just tested the script locally ./openshift/in-docker-patch.sh" works :fine thinking: Could we get the script output?

**Comment by skonto** [comment]
Hm dockerbuild probably fails due to the relative path. I will check.

**Comment by skonto** [comment]
No it should work in all dockerfiles we have access to the files as usual:

```
COPY . .
...
RUN go build -tags strictfipsruntime -o /usr/bin/main ./cmd/activator
```
Not sure why this should not work.

**Comment by skonto** [comment]
```
+ git apply ./openshift/patches/001-object.patch
error: patch failed: vendor/knative.dev/pkg/test/helpers/name.go:26
error: vendor/knative.dev/pkg/test/helpers/name.go: patch does not apply
+ git apply ./openshift/patches/002-mutemetrics.patch
error: patch failed: vendor/knative.dev/pkg/controller/stats_reporter.go:199
error: vendor/knative.dev/pkg/controller/stats_reporter.go: patch does not apply
+ git apply ./openshift/patches/003-routeretry.patch
error: vendor/knative.dev/pkg/test/spoof/openshift_checks.go: already exists in working directory
error: patch failed: vendor/knative.dev/pkg/test/spoof/spoof.go:164
error: vendor/knative.dev/pkg/test/spoof/spoof.go: patch does not apply
+ git add .
```

**Comment by skonto** [comment]
@pierDipi is not builds based on source code isolated https://console.redhat.com/application-pipeline/workspaces/ocp-serverless/applications/serverless-operator-135/pipelineruns/kn-serving-dataplane-probe-115-on-pull-request-pxqgl/logs?task=build-images?

**Comment by skonto** [comment]
Discussion [here](https://redhat-internal.slack.com/archives/CF5ANN61F/p1728651485494129), will discuss on Monday what we should do with those images as it is an overhead to keep them. QE uses Influxdb.

**Comment by ReToCode** [comment]
```
Failed to create PVC for PipelineRun ocp-serverless-tenant/kn-serving-test-volumes-115-on-pull-request-xvlrw correctly: PVC creation error: failed to create PVC pvc-7a570c0aeb: persistentvolumeclaims "pvc-7a570c0aeb" is forbidden: exceeded quota: storage, requested: count/persistentvolumeclaims=1, used: count/persistentvolumeclaims=360, limited: count/persistentvolumeclaims=360
```

**Comment by skonto** [comment]
/override "Red Hat Konflux / kn-serving-activator-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-autoscaler-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-autoscaler-hpa-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-cleanup-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-controller-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-dataplane-probe-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-default-domain-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-load-test-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-queue-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-real-traffic-test-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-reconciliation-delay-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-rollout-probe-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-scale-from-zero-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-storage-version-migration-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-autoscale-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-failing-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-grpc-ping-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-hellohttp2-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-hellovolume-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-helloworld-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-httpproxy-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-pizzaplanetv1-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-pizzaplanetv2-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-readiness-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-revisionfailure-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-runtime-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-servingcontainer-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-sidecarcontainer-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-singlethreaded-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-slowstart-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-timeout-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-volumes-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-wsserver-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-webhook-115-on-pull-request"

**Pull request merged**
