### PR TITLE
[RELEASE-v1.15] Update golang.org/x/crypto to 0.31.0

### PR DESCRIPTION
**Pull request by skonto**
**What this PR does / why we need it**:

See discussion [here](https://redhat-internal.slack.com/archives/CKR568L8G/p1734423301601539).

**Which issue(s) this PR fixes**:

JIRA:

**Does this PR needs for other branches**:

**Does this PR (patch) needs to update/drop in the future?**:

JIRA:

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
```
            "message": "domain name error: invalid domain name \"autoscale-sustaining-aggregation-weighted-qhcowhbl-serving-tests.apps.serverless-ocp-4-17-amd64-aws-us-east-1-ptppr.serverless.devcluster.openshift.com\": url: Invalid value: \"autoscale-sustaining-aggregation-weighted-qhcowhbl-serving-tests\": must be no more than 63 characters",
```

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-activator-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-hpa-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-cleanup-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-controller-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-dataplane-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-default-domain-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-load-test-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-queue-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-real-traffic-test-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-reconciliation-delay-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-rollout-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-scale-from-zero-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-storage-version-migration-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-autoscale-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-failing-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-grpc-ping-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-hellohttp2-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-hellovolume-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-helloworld-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-httpproxy-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv1-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv2-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-readiness-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-revisionfailure-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-runtime-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-servingcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-sidecarcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-singlethreaded-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-slowstart-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-timeout-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-volumes-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-wsserver-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-webhook-115"

**Comment by skonto** [comment]
/override "Red Hat Konflux / kn-serving-load-test-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-autoscale-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-grpc-ping-115-on-pull-request"
/override "Red Hat Konflux / kn-serving-test-hellohttp2-115-on-pull-request"

**Comment by skonto** [comment]
For the tls tests the error I see:
```
            "message": "domain name error: invalid domain name \"multi-container-readiness-different-probe-gvictkxs-serving-tests.apps.serverless-ocp-4-17-amd64-aws-us-east-1-n5vv7.serverless.devcluster.openshift.com\": url: Invalid value: \"multi-container-readiness-different-probe-gvictkxs-serving-tests\": must be no more than 63 characters",
``

**Comment by skonto** [comment]
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-activator-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-autoscaler-hpa-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-cleanup-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-controller-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-dataplane-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-default-domain-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-queue-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-real-traffic-test-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-reconciliation-delay-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-rollout-probe-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-scale-from-zero-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-storage-version-migration-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-failing-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-hellovolume-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-helloworld-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-httpproxy-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv1-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-pizzaplanetv2-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-readiness-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-revisionfailure-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-runtime-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-servingcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-sidecarcontainer-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-singlethreaded-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-slowstart-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-timeout-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-volumes-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-test-wsserver-115"
/override "Red Hat Konflux / serverless-operator-135-ec / kn-serving-webhook-115"

**Pull request merged**
