### PR TITLE
Update image base Golang to 1.22

### PR DESCRIPTION
**Pull request by dsimansk**
/cc @ReToCode

### CODE REVIEW

**Comment by dsimansk** [comment]
@ReToCode do we need to update perf test images. They are not included in `make generate-dockerfiles`.

**Comment by ReToCode** [comment]
>  do we need to update perf test images? They are not included in make generate-dockerfiles.

I think so yes. @skonto WDYT?

**Comment by dsimansk** [comment]
The Golang images needs to be merged first to pass setup through S-O. 

```
./hack/update-deps.sh
invalid value "1.22" for flag -compat: maximum supported Go version is 1.21.11
usage: go mod tidy [-e] [-v] [-x] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
```

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
