### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/main

### PR DESCRIPTION
**Pull request by serverless-qe**

### CODE REVIEW

**Comment by skonto** [comment]
```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}
```

**Comment by skonto** [comment]
`{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}`

**Comment by skonto** [comment]
```
{  failed to list cluster pools with list option map[architecture:amd64 cloud:aws owner:serverless-ci product:ocp version:4.15]: failed to get API group resources: unable to retrieve the complete list of server APIs: hive.openshift.io/v1: Get "https://api.hosted-mgmt.ci.devcluster.openshift.com:6443/apis/hive.openshift.io/v1": tls: failed to verify certificate: x509: certificate signed by unknown authority}
```

**Comment by skonto** [comment]
```
{  "test-e2e-aws-415" test steps failed: "test-e2e-aws-415" pod "test-e2e-aws-415-test" failed: could not watch pod: the pod ci-op-g7ctmi8v/test-e2e-aws-415-test failed after 4m17s (failed containers: test): ContainerFailed one or more containers exited
```

**Comment by skonto** [comment]
This passed locally, trying again.

**Comment by ReToCode** [comment]
no idea, that sounds fishy:

```
fatal: ambiguous argument ':(glob)**/*.go': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```

Let's close this one and get a fresh one tomorrow.

**Pull request closed without merging**
