### PR TITLE
[RELEASE-1.14] Backport: Integrate net-certmanager in Serving

### PR DESCRIPTION
**Pull request by ReToCode**
# Changes
- Backport of https://github.com/knative/serving/pull/15066

/assign @skonto

### CODE REVIEW

**Comment by ReToCode** [comment]
/override "Validate / Lint"

weird GH stuff again.

**Comment by skonto** [comment]
@ReToCode let's wait for the CI?

**Comment by ReToCode** [comment]
https://github.com/openshift/release/pull/51451

**Comment by ReToCode** [comment]
@skonto now with CI, we skip tls stuff, as it needs S-O changes. I'll work on those next.

**Pull request merged**
